# Install script for directory: /home/jth39/Documents/other/cgal/examples

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/jth39/Documents/other/cgal/examples/examples/AABB_tree/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Advancing_front_surface_reconstruction/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Algebraic_foundations/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Algebraic_kernel_d/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Alpha_shapes_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Alpha_shapes_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Apollonius_graph_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Approximate_min_ellipsoid_d/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Arrangement_on_surface_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/BGL_arrangement_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/BGL_polyhedron_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/BGL_surface_mesh/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/BGL_triangulation_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Barycentric_coordinates_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Boolean_set_operations_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Box_intersection_d/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/CGAL_ipelets/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/CGALimageIO/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Circular_kernel_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Circular_kernel_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Circulator/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Combinatorial_map/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Convex_decomposition_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Convex_hull_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Convex_hull_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Core/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Envelope_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Envelope_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Filtered_kernel/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Generator/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/HalfedgeDS/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Inscribed_areas/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Interpolation/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Interval_skip_list/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Jet_fitting_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Kernel_23/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Kinetic_data_structures/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Kinetic_framework/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Linear_cell_complex/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Matrix_search/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Mesh_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Mesh_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Min_annulus_d/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Min_circle_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Min_ellipse_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Min_quadrilateral_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Min_sphere_d/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Min_sphere_of_spheres_d/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Minkowski_sum_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Minkowski_sum_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Modular_arithmetic/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Nef_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Nef_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Nef_S2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Partition_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Periodic_2_triangulation_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Periodic_3_triangulation_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Point_set_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Point_set_processing_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Point_set_shape_detection_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Polygon/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Polygon_mesh_processing/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Polyhedron/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Polyhedron_IO/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Polyline_simplification_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Polynomial/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Polytope_distance_d/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Principal_component_analysis/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Profiling_tools/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/QP_solver/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/RangeSegmentTrees/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Rectangular_p_center_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Ridges_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/STL_Extension/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Scale_space_reconstruction_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Segment_Delaunay_graph_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Segment_Delaunay_graph_Linf_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Skin_surface_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Snap_rounding_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Spatial_searching/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Spatial_sorting/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Straight_skeleton_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Stream_lines_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Subdivision_method_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Surface_mesh/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Surface_mesh_parameterization/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Surface_mesh_segmentation/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Surface_mesh_shortest_path/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Surface_mesh_simplification/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Surface_mesh_skeletonization/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Surface_mesher/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Surface_modeling/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Surface_reconstruction_points_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Triangulation/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Triangulation_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Triangulation_3/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Visibility_2/cmake_install.cmake")
  include("/home/jth39/Documents/other/cgal/examples/examples/Voronoi_diagram_2/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/home/jth39/Documents/other/cgal/examples/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
